spring.application.name=Devpulse

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.format_sql=true

spring.security.jwt.secret={JWT_SECRET}
spring.security.jwt.issuer=Devpulse
spring.security.jwt.access-ttl-seconds=60000
spring.security.jwt.refresh-ttl-seconds=86400

spring.security.jwt.refresh-token-cookie-name=refreshToken
spring.security.jwt.cookie-secure=false
spring.security.jwt.cookie-same-site=Lax
spring.security.jwt.cookie-http-only=true
spring.security.jwt.cookie-domain=

spring.ai.google.genai.api-key=${API_KEY}
spring.ai.google.genai.chat.model=gemini-2.5-flash

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_SECRET_ID}
spring.security.oauth2.client.registration.google.scope=email,profile,openid

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_SECRET_ID}
spring.security.oauth2.client.registration.github.scope=user:email,read:user

spring.auth.app.cors.frontend.url=http://localhost:5173
spring.app.auth.frontend.success-url=http://localhost:5173/oauth-success
spring.app.auth.frontend.failure-url=http://localhost:5173/login?error=oauth_failed

